### ISSUE TITLE
DiscordJS V13

### ISSUE THREAD

**Issue by Stefouch** [HunterLarco/treachery.bot#21]
Just a small warning for you, it looks like you still use DiscordJS V12, which is outdated (and even unstable with the latest Discord API V9).

For example, I have also a discord bot, and I was forced to update it to DiscordJS V13 due to random crashes (see [here](https://github.com/Stefouch/sebedius-yearzero-discord-bot/issues/133)).

Guide: [Updating from v12 to v13](https://discordjs.guide/additional-info/changes-in-v13.html#before-you-start).

**Comment by HunterLarco** [comment]
Resolved in #22
